### ISSUE TITLE
README.md本地ip查询命令好像少了'

### ISSUE THREAD

**Issue by wangangran** [macaujack/aliyun_ddns#2]
ip -6 addr show wlp4s0 | sed -nE 's/^.*inet6.*(2408[0-9a-f:]+).*mngtmpaddr.*$/\1/p
改为
ip -6 addr show wlp4s0 | sed -nE 's/^.*inet6.*(2408[0-9a-f:]+).*mngtmpaddr.*$/\1/p'

**Comment by macaujack** [comment]
确实是少了一个单引号，现在加上去了，谢谢 :)
